// Code generated by fabricator-generate-go
//
// Modifications in code regions will be lost during regeneration!
package fabricatorgeneratetoolgo

// region CODE_REGION(GEN)
//go:generate fabricator generate go
//go:generate fabricator generate project go
//go:generate fabricator generate plugin go
// endregion
