// Code generated by fabricator-generate-project-go
//
// Modifications in code regions will be lost during regeneration!
// region CODE_REGION(name)
module code.cestus.io/tools/fabricator-generate-tool-go

go 1.21

// endregion

require (
	code.cestus.io/libs/buildinfo v0.0.1
	code.cestus.io/libs/codegenerator v0.1.0
	code.cestus.io/tools/fabricator v0.3.1
	github.com/onsi/ginkgo/v2 v2.12.0
	github.com/onsi/gomega v1.28.0
	github.com/spf13/cobra v1.8.0
	github.com/spf13/pflag v1.0.5
	gopkg.in/yaml.v3 v3.0.1
)

require (
	github.com/Masterminds/goutils v1.1.1 // indirect
	github.com/Masterminds/semver/v3 v3.2.0 // indirect
	github.com/Masterminds/sprig/v3 v3.2.3 // indirect
	github.com/Scardiecat/svermaker v0.4.1 // indirect
	github.com/blang/semver/v4 v4.0.0 // indirect
	github.com/go-logr/logr v1.3.0 // indirect
	github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572 // indirect
	github.com/google/go-cmp v0.6.0 // indirect
	github.com/google/pprof v0.0.0-20210407192527-94a9f03dee38 // indirect
	github.com/google/uuid v1.1.1 // indirect
	github.com/google/wire v0.5.0 // indirect
	github.com/huandu/xstrings v1.3.3 // indirect
	github.com/imdario/mergo v0.3.11 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/mitchellh/copystructure v1.0.0 // indirect
	github.com/mitchellh/reflectwalk v1.0.0 // indirect
	github.com/shopspring/decimal v1.2.0 // indirect
	github.com/sirupsen/logrus v1.8.1 // indirect
	github.com/spf13/cast v1.3.1 // indirect
	golang.org/x/crypto v0.14.0 // indirect
	golang.org/x/net v0.17.0 // indirect
	golang.org/x/sys v0.14.0 // indirect
	golang.org/x/text v0.14.0 // indirect
	golang.org/x/tools v0.14.0 // indirect
)
