// Code generated by fabricator-generate-plugin-go
//
// Modifications in code regions will be lost during regeneration!

package fabricatorgeneratetoolgo

import (
	"fmt"
	"io"

	"code.cestus.io/tools/fabricator/pkg/fabricator"
	"gopkg.in/yaml.v3"
)

type PinDependency struct {
	Name    string `yaml:"name" json:"name"`
	Version string `yaml:"version" json:"version"`
}

type ToolDependency struct {
	Name string `yaml:"name" json:"name"`
}

type PinDependencies map[string]PinDependency

type ReplaceDependencies map[string]ReplaceDependency

type ToolDependencies map[string]ToolDependency

type ReplaceDependency struct {
	Name string `yaml:"name" json:"name"`
	With string `yaml:"with" json:"with"`
}

// Spec contains the specification for the plugin
type Spec struct {
	PinDependency     PinDependencies     `yaml:"pinDependency,omitempty" json:"pinDependency,omitempty"`
	ReplaceDependency ReplaceDependencies `yaml:"replaceDependency,omitempty" json:"replaceDependency,omitempty"`
	ToolDependency    ToolDependencies    `yaml:"toolDependency,omitempty" json:"toolDependency,omitempty"`

	ExampleValue string `yaml:"exampleValue" json:"exampleValue"`
}

// region CODE_REGION(PLUGIN_COMPONENT)
type PluginComponent struct {
	Name      string `yaml:"name" json:"name"`
	Generator string `yaml:"generator" json:"generator"`
	Spec      Spec   `yaml:"spec" json:"spec"`
}

type PluginComponents []PluginComponent

type PluginConfig struct {
	ApiVersion string           `yaml:"apiVersion" json:"apiVersion"`
	Kind       string           `yaml:"kind" json:"kind"`
	Components PluginComponents `yaml:"components" json:"components"`
}

func LoadPluginConfig(r io.Reader) (PluginConfig, error) {
	pluginConfig := PluginConfig{}
	var err error
	if err = yaml.NewDecoder(r).Decode(&pluginConfig); err != nil {
		return pluginConfig, fmt.Errorf("failed to decode pluginConfig %s", err)
	}

	return pluginConfig, err
}

// endregion

func (s *PluginConfig) UnmarshalYAML(value *yaml.Node) error {

	var config fabricator.FabricatorConfig
	if err := value.Decode(&config); err != nil {
		return err
	}
	s.ApiVersion = config.ApiVersion
	s.Kind = config.Kind

	for _, component := range config.Components {

		if component.Generator != PluginName {
			continue
		}
		spec := Spec{}
		err := component.Spec.Decode(&spec)
		if err != nil {
			return err
		}
		plComponent := PluginComponent{
			Name:      component.Name,
			Generator: component.Generator,
			Spec:      spec,
		}
		s.Components = append(s.Components, plComponent)
	}
	return nil
}
