// Code generated by fabricator-generate-plugin-go
//
// DO NOT EDIT.

package fabricatorgeneratetoolgo

import (
	"context"
	"os"
	"path"

	"code.cestus.io/libs/codegenerator/pkg/templating"
	"code.cestus.io/tools/fabricator/pkg/fabricator"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"code.cestus.io/tools/fabricator-generate-tool-go/pkg/fabricator-generate-tool-go/templates"
)

var _ = Describe("Generation", func() {
	It("Generates", func() {
		ctx := context.Background()
		packProvider := templating.NewPackProvider()
		packProvider.RegisterProvider(templating.NewEmbededPackProvider(templates.GetTemplates()))
		io := fabricator.NewGinkoTestIOStreams()
		file, err := os.Open("./testdata/deserialize.yml")
		Expect(err).ToNot(HaveOccurred())
		config, err := LoadPluginConfig(file)
		Expect(err).ToNot(HaveOccurred())
		root, err := os.MkdirTemp("./testdata", "generation")
		Expect(err).ToNot(HaveOccurred())
		// add go mod
		gomod, err := os.Create(path.Join(root, "go.mod"))
		Expect(err).ToNot(HaveOccurred())
		defer gomod.Close()
		gomod.WriteString("module example.com/testmodule\n")
		gomod.WriteString("go 1.18\n")
		plugin, err := newPlugin(ctx, io, config, root, packProvider)
		Expect(err).ToNot(HaveOccurred())
		err = plugin.Generate(ctx, io)
		Expect(err).ToNot(HaveOccurred())
		err = os.RemoveAll(root)
		Expect(err).ToNot(HaveOccurred())
	})
})
