// Code generated by fabricator-generate-plugin-go
//
// Modifications in code regions will be lost during regeneration!

package fabricatorgeneratetoolgo

// region CODE_REGION(PINS)

var DefaultPins PinDependencies = PinDependencies{
	// endregion
	//
	//	"go.opentelemetry.io/otel": {
	//		Name:    "go.opentelemetry.io/otel",
	//		Version: "v0.20.0",
	//	},
}

// region CODE_REGION(replacements)
var DefaultReplacements ReplaceDependencies = ReplaceDependencies{
	// endregion
	//
	//	"github.com/onsi/ginkgo": {
	//		Name: "github.com/onsi/ginkgo",
	//		With: "github.com/magicmoose/ginkgo@v1.17.0",
	//	},
}

// region CODE_REGION(tooldeps)
var DefaultToolDependencies ToolDependencies = ToolDependencies{
	//endregion
	"github.com/onsi/ginkgo/v2": {
		Name: "github.com/onsi/ginkgo/v2/ginkgo",
	},
	"github.com/google/wire": {
		Name: "github.com/google/wire",
	},
	"github.com/google/wire/cmd/wire": {
		Name: "github.com/google/wire/cmd/wire",
	},
}

//endregion
