// Code generated by fabricator-generate-plugin-go
//
// Modifications in code regions will be lost during regeneration!

package fabricatorgeneratetoolgo_test

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"testing"
)

func TestFabricatorGenerateToolGo(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "FabricatorGenerateToolGo Suite")
}
